### ISSUE TITLE
`JSON.stringify` fails to serialize

### ISSUE THREAD

**Issue by kevzzsk** [node-cache-manager/node-cache-manager-ioredis-yet#324]
This `getVal` is not customisable leading to some value such as `bigint` to fail to serialize. 
`const getVal = (value: unknown) => JSON.stringify(value) || '"undefined"';`

We can allow custom `transformValue` function that can be passed into the `options` and default to `getVal` if nothing is passed. This will allow custom serialization of cached data.

**Comment by abdelhalim97** [comment]
hello @kevzzsk 
i can confirm that the @interceptor not able to cache almost all my responses because my msql database works with bigint 
if there s a function to customize the stringify operation that it happens under the hood, will solve the issue.
@kevzzsk thanks for helping me notice that the problem is the bigint i spent my full day trying to find out why only empty responses are getting cached.

**Comment by andreialecu** [comment]
#327 is also related to this problem but should be of higher frequency.
